/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demo.ui;
import RepositoryMantenimiento.Manteni_Cliente;
import javax.swing.DefaultListModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
//import com.kiaRepositorio.ClienteRepositorio;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import identidades.Clientes;


/**
 *
 * @author USUARIO
 */
public class Cliente extends javax.swing.JFrame {

Manteni_Cliente mc=new Manteni_Cliente();

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        txtId_Cliente.setVisible(false);
       // Conn=ClienteRepositorio.
       
    }

    private Cliente(int i, String text, String text0, String text1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCorreoElectronico = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        txtId_Cliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CLIENTE");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Nombres");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Apellidos");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Correo Electronico");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Direccion");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Telefono");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Cedula");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 181, -1));

        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        jPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 181, -1));

        txtCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoElectronicoActionPerformed(evt);
            }
        });
        txtCorreoElectronico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoElectronicoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 200, 30));

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        jPanel2.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 127, -1));

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 230, 30));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 120, -1));

        btnAñadir.setBackground(new java.awt.Color(255, 204, 204));
        btnAñadir.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(204, 0, 0));
        btnAñadir.setText("AÑADIR");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel2.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, 40));
        jPanel2.add(txtId_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 30, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprar-coche-internet.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 430, 350));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 454, 380));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoElectronicoActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        identidades.Clientes cl=new identidades.Clientes(txtNombres.getText(),txtCedula.getText(),txtDireccion.getText(),txtCorreoElectronico.getText(),txtApellidos.getText(),txtTelefono.getText());
        mc.Grabar(cl);
        if(txtNombres.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por Favor Ingrese Su Nombre ");
            return;
        }
        if(txtApellidos.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor ingrese su Apellido ");
            return;
        }
        if(txtCorreoElectronico.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por Favor Ingrese Su Correo Electronico");
            return;
        }
    
            if(txtCedula.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Por Favor Ingrese Su Numero De Cedula");
            return;
            }
            if(txtDireccion.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Por Favor Ingrese Su Direccion ");
            return;
            }
            if(txtTelefono.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Por Favor Ingrese Su Numero De Telefono");
            return;
            }
            
         String Nombres,Apellidos,CorreoElectronico,Cedula,Telefono,Direccion;
         
         Nombres=txtNombres.getText();
         Apellidos=txtApellidos.getText();
         CorreoElectronico=txtCorreoElectronico.getText();
         Cedula=txtCedula.getText();
         Direccion=txtDireccion.getText();
         Telefono=txtTelefono.getText();
        
         
         JOptionPane.showMessageDialog(null, "Nombres:"+Nombres+"Apellidos:"+Apellidos+"Correo Electronico:"+CorreoElectronico+"Cedula:"+Cedula+"Telefono:"+Telefono+"Direccion:"+Direccion);
          
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCorreoElectronico.setText("");
        txtCedula.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        if(txtCedula.getText().length()>=10){
            evt.consume();
        }
        char TipoDeTecla=evt.getKeyChar();
        if(!Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
        Character c=TipoDeTecla=evt.getKeyChar();
				if(Character.isLetter(c)){
					getToolkit().beep();
					evt.consume();
					JOptionPane.showMessageDialog(null, "Ingrese solo números por favor");
                                }
    
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        // TODO add your handling code here:
        if(txtNombres.getText().length()>=25){
            JOptionPane.showMessageDialog(rootPane, "solo son 25 letras");
            evt.consume();
        }
        char TipoDeTecla=evt.getKeyChar();
        if(Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
        Character c=TipoDeTecla=evt.getKeyChar();
				if(Character.isDigit (c)){
					getToolkit().beep();
					evt.consume();
					JOptionPane.showMessageDialog(null, "Ingrese solo letras por favor");
				}


    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        // TODO add your handling code here:
        if(txtApellidos.getText().length()>=25){
            evt.consume();
        }
        char TipoDeTecla=evt.getKeyChar();
        if(Character.isDigit(TipoDeTecla)){
        evt.consume();
        }
        Character c=TipoDeTecla=evt.getKeyChar();
				if(Character.isDigit (c)){
					getToolkit().beep();
					evt.consume();
					JOptionPane.showMessageDialog(null, "Ingrese solo letras por favor");
				}
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtCorreoElectronicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoElectronicoKeyTyped
        // TODO add your handling code here:
        if(txtCorreoElectronico.getText().length()>30){
            evt.consume();
        }
        char TipoDeTecla=evt.getKeyChar();
        if(Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtCorreoElectronicoKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        // TODO add your handling code here:
         if(txtDireccion.getText().length()>=25){
            evt.consume();
        }
        char TipoDeTecla=evt.getKeyChar();
        if(Character.isDigit(TipoDeTecla)){
          evt.consume();
        }
        Character c=TipoDeTecla=evt.getKeyChar();
				if(Character.isDigit (c)){
					getToolkit().beep();
					evt.consume();
					JOptionPane.showMessageDialog(null, "Ingrese solo letras por favor");
				}
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        if(txtTelefono.getText().length()>=10){
            evt.consume();
        }
        char TipoDeTecla=evt.getKeyChar();
        if(!Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
        Character c=TipoDeTecla=evt.getKeyChar();
				if(Character.isLetter(c)){
					getToolkit().beep();
					evt.consume();
					JOptionPane.showMessageDialog(null, "Ingrese solo números por favor");
                                }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        Clientes cl= mc.Consultar(txtCedula.getText());
        
        txtNombres.setText(cl.getNombres());
        txtCedula.setText(cl.getCedula());
        txtDireccion.setText(cl.getDireccion());
        txtCorreoElectronico.setText(cl.getCorreo_electronico());
        txtApellidos.setText(cl.getApellidos());
        txtTelefono.setText(cl.getTelefono());
        txtId_Cliente.setText(Integer.toString(cl.getId_cliente()));
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        // TODO add your handling code here:
     new Factura().setVisible(true);
     this.setVisible(false);
        Factura.txtCliente.setText(txtNombres.getText()+" "+txtApellidos.getText() );
      Factura.txtCedula.setText(txtCedula.getText());
      Factura.txtDireccion.setText(txtDireccion.getText());
      Factura.txtNombres.setText(txtNombres.getText());
    }//GEN-LAST:event_btnAñadirActionPerformed
                        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId_Cliente;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    public void Guardar(){
        conexion cn= new conexion();
        try{
            Connection cone= cn.conexion();
            PreparedStatement ps= cone.prepareStatement("INSERT INTO cliente (nombres,cedula,direccion, correo_electronico,apellidos,telefono ) VALUES (?,?,?,?,?,?)");
            ps.setString(1, txtNombres.getText());
            ps.setString(2, txtCedula.getText());
            ps.setString(3, txtDireccion.getText());
            ps.setString(4, txtCorreoElectronico.getText());
            ps.setString(5, txtApellidos.getText());
            ps.setString(6, txtTelefono.getText());
            ps.executeUpdate();
    }catch(SQLException ex){
        System.out.println(ex.getMessage());
    }
    }
    public void Consultar(){
        conexion cn= new conexion();
        try{
            Connection cone= cn.conexion();
            PreparedStatement ps= cone.prepareCall("SELECT * FROM cliente where cedula='"+txtCedula.getText()+"'");
            ResultSet rst= ps.executeQuery();
            if(rst.next()){
            txtNombres.setText(rst.getString(1));
            txtCedula.setText(rst.getString(2));
            txtDireccion.setText(rst.getString(3));
            txtCorreoElectronico.setText(rst.getString(4));
            txtApellidos.setText(rst.getString(5));
            txtTelefono.setText(rst.getString(6));
            }else{
                JOptionPane.showMessageDialog(null, "El cliente no se encuentra registrado", "Error", JOptionPane.ERROR_MESSAGE);   
            }
        }catch(SQLException ex){
           System.out.println(ex.getMessage());
        }
    }
}
