/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demo.ui;


import RepositoryMantenimiento.manty_Producto;
import identidades.Producto;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Productos extends javax.swing.JFrame {
manty_Producto mpro=new manty_Producto();
    /**
     * Creates new form Producto
     */
    public Productos() {
        initComponents();
    }

    private Productos(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        filtro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnaBuscar = new javax.swing.JButton();
        cbfiltro = new javax.swing.JComboBox<>();
        txtParametro = new javax.swing.JTextField();
        chTodo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProducto = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Producto");

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));

        filtro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        filtro.setForeground(new java.awt.Color(153, 0, 153));
        filtro.setText("Filtro");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Parametro");

        btnaBuscar.setBackground(new java.awt.Color(153, 153, 255));
        btnaBuscar.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        btnaBuscar.setForeground(new java.awt.Color(0, 0, 204));
        btnaBuscar.setText("BUSCAR");
        btnaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaBuscarActionPerformed(evt);
            }
        });

        cbfiltro.setBackground(new java.awt.Color(204, 255, 255));
        cbfiltro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbfiltro.setForeground(new java.awt.Color(153, 0, 153));
        cbfiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Marca", "Cantidad", "Precio" }));

        chTodo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        chTodo.setForeground(new java.awt.Color(153, 0, 153));
        chTodo.setText("Todo");
        chTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(filtro)
                        .addGap(36, 36, 36)
                        .addComponent(cbfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chTodo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 71, Short.MAX_VALUE)
                        .addComponent(btnaBuscar)
                        .addGap(19, 19, 19))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtro)
                    .addComponent(cbfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chTodo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtParametro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(btnaBuscar))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        tbProducto.setBackground(new java.awt.Color(153, 204, 255));
        tbProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbProducto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tbProducto.setForeground(new java.awt.Color(153, 0, 153));
        tbProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Marca", "Cantidad", "Precio"
            }
        ));
        tbProducto.setGridColor(new java.awt.Color(51, 51, 51));
        tbProducto.setSelectionForeground(new java.awt.Color(51, 102, 255));
        jScrollPane1.setViewportView(tbProducto);

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(102, 204, 255));
        jPanel3.setFocusCycleRoot(true);
        jPanel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btnLimpiar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(153, 0, 153));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnAñadir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(153, 0, 153));
        btnAñadir.setText("AÑADIR");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLimpiar)
                .addGap(18, 18, 18)
                .addComponent(btnAñadir)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Cantidad");

        btnSalir.setBackground(new java.awt.Color(153, 153, 255));
        btnSalir.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 0, 0));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/huii.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addGap(238, 238, 238)))
                        .addComponent(jLabel3)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidad)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaBuscarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel te=(DefaultTableModel)tbProducto.getModel();
        te.setRowCount(0);
        if(chTodo.isSelected()){
            BuscarTodo();
            
        }else{
            if(txtParametro.getText().equals("")|| (cbfiltro.getSelectedIndex()==-1)){
                JOptionPane.showMessageDialog(null,"ERROR:Debe Poner Al Menos Un Parametro","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                switch (cbfiltro.getSelectedIndex()){
                    case 0:
                      busqueda1();
                      break;
                    case 1:
                        busqueda2();
                        break;
                    case 2:
                        busqueda3();
                        break;
                    case 3:
                        busqueda4();
                        break;
                }
               
                
            }
        }
        
    }//GEN-LAST:event_btnaBuscarActionPerformed

    private void chTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chTodoActionPerformed
        // TODO add your handling code here:
        if(chTodo.isSelected()){
            cbfiltro.setEnabled(false);
            txtParametro.setEnabled(false);
        }else{
          
            cbfiltro.setEnabled(true);
            txtParametro.setEnabled(true);  
          }
          
    }//GEN-LAST:event_chTodoActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
    int c=0;
        Object pro[]=new Object[tbProducto.getColumnCount()];  
        while(c<pro.length){
            
            pro[c]=tbProducto.getValueAt(tbProducto.getSelectedRow(),c);
            c++;
        }
    
    this.setVisible(false);
        DefaultTableModel sc =(DefaultTableModel) Factura.tb1.getModel();
        pro[2]=txtCantidad.getText();
    sc.addRow(pro);
    Factura.tb1.setModel(sc);
   
    }//GEN-LAST:event_btnAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnaBuscar;
    private javax.swing.JComboBox<String> cbfiltro;
    private javax.swing.JCheckBox chTodo;
    private javax.swing.JLabel filtro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbProducto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtParametro;
    // End of variables declaration//GEN-END:variables

 conexion conecta=new conexion();
    Connection conex= conecta.conexion();
    
     private void Limpiar(){
     txtParametro.getText();
     cbfiltro.addItem("");
     }
    
    public void busqueda1(){
    Object parametro="'"+txtParametro.getText()+"'";
        String SQL="SELECT producto.*,proveedor.* FROM producto inner join proveedor on producto.id_proveedor=proveedor.id_proveedor WHERE producto.nombre="+parametro;
    DefaultTableModel te=(DefaultTableModel)tbProducto.getModel();
    
    List<Producto> po=mpro.ObtenerProductos(SQL);
   
      Object ma[]=new Object[4];
   for(Producto py:po){
       ma[0]=py.getNombre();
                 ma[1]=py.getMarca();
                 ma[2]=py.getCantidad();
                 ma[3]=py.getPrecio();
                 te.addRow(ma);
   }              

            tbProducto.setModel(te);
}
public void BuscarTodo(){
    DefaultTableModel te=(DefaultTableModel)tbProducto.getModel();
    String SQL="SELECT producto.*,proveedor.* FROM producto inner join proveedor on producto.id_proveedor=proveedor.id_proveedor";
    List<Producto> po=mpro.ObtenerProductos(SQL);
   
      Object ma[]=new Object[4];
   for(Producto py:po){
       ma[0]=py.getNombre();
                 ma[1]=py.getMarca();
                 ma[2]=py.getCantidad();
                 ma[3]=py.getPrecio();
                 te.addRow(ma);
   }              

            tbProducto.setModel(te);
           
}
public void busqueda2(){
    Object parametro="'"+txtParametro.getText()+"'";
        String SQL="SELECT producto.*,proveedor.* FROM producto inner join proveedor on producto.id_proveedor=proveedor.id_proveedor WHERE producto.marca="+parametro;
    DefaultTableModel te=(DefaultTableModel)tbProducto.getModel();
    
    List<Producto> po=mpro.ObtenerProductos(SQL);
   
      Object ma[]=new Object[4];
   for(Producto py:po){
       ma[0]=py.getNombre();
                 ma[1]=py.getMarca();
                 ma[2]=py.getCantidad();
                 ma[3]=py.getPrecio();
                 te.addRow(ma);
   }              

            tbProducto.setModel(te);
}

public void busqueda3(){
    Object parametro="'"+txtParametro.getText()+"'";
        String SQL="SELECT producto.*,proveedor.* FROM producto inner join proveedor on producto.id_proveedor=proveedor.id_proveedor WHERE producto.cantidad="+parametro;
    DefaultTableModel te=(DefaultTableModel)tbProducto.getModel();
    
    List<Producto> po=mpro.ObtenerProductos(SQL);
   
      Object ma[]=new Object[4];
   for(Producto py:po){
       ma[0]=py.getNombre();
                 ma[1]=py.getMarca();
                 ma[2]=py.getCantidad();
                 ma[3]=py.getPrecio();
                 te.addRow(ma);
   }              

            tbProducto.setModel(te);
}
public void busqueda4(){
    Object parametro=txtParametro.getText();
        String SQL="SELECT producto.*,proveedor.* FROM producto inner join proveedor on producto.id_proveedor=proveedor.id_proveedor WHERE producto.precio="+parametro;
    DefaultTableModel te=(DefaultTableModel)tbProducto.getModel();
    
    List<Producto> po=mpro.ObtenerProductos(SQL);
   
      Object ma[]=new Object[4];
   for(Producto py:po){
       ma[0]=py.getNombre();
                 ma[1]=py.getMarca();
                 ma[2]=py.getCantidad();
                 ma[3]=py.getPrecio();
                 te.addRow(ma);
   }              

            tbProducto.setModel(te);
}
public void limpiar(){
    cbfiltro.setSelectedIndex(-1);
    txtParametro.setText("");
   DefaultTableModel tb= (DefaultTableModel) tbProducto.getModel();
   tb.setRowCount(0);
   tbProducto.setModel(tb);
}
}